### ISSUE TITLE
tama_merge.py collapse_transcript bug for uneven exon counts

### ISSUE THREAD

**Issue by petersbr** [GenomeRIK/tama#1]
Hi,

I've encountered a bug in the collapse_transcript in the section that starts with the following code:
`
for i in xrange(max_exon_num): #go from 3 prime end
`

A downstream KeyError will occur when accessing the  results returned from the lists created by the following two lines because best_e_start and best_e_end are not guaranteed to get set to a real start or end, they may stay as their originally initialized -1 or 0:
`       collapse_start_list.append(best_e_start)`
`        collapse_end_list.append(best_e_end) `
The issue arises when using varied weights for different gene model sets.  

Imagine that you are merging two transcripts in the forward strand (though the real life example I've explored has been in the minus strand):

Transcript | StartPriority | EndPriority | JxnPriority | Exon Chain
 ---------- | ------------- | ------------ | ----------- | -------------
A | 1 | 2 | 1 |  (20, 30), (40, 50)
B | 2 | 1 | 1 |  (20,30),  (40-50), (60-70)

What gets reported is something like:  
  Starts: 20, 40, 60
  Ends:  30, 50, 0
Those are then subsequently sorted and when the calling function tries to look up a value for -1 or 0, it doesn't exist in the dictionary and the program dies. 

I'll work around it for now by just setting all the priorities to be equal so I can take advantage of the voting by junction counts.

Hope this is enough to figure out the issue.

**Comment by GenomeRIK** [comment]
Hello, thank you for pointing this out. Do you mind sending me the lines from the input files which are causing this issue?

**Comment by GenomeRIK** [comment]
Hi Peter,

I found the issue you encountered and I have fixed it. Let me know if it works for you now.

Thank you,
Richard

**Comment by petersbr** [comment]
Thank you for fixing this!  I am closing this as the original data is gone now and it will be several months before I have new data to work with.
