### ISSUE TITLE
question on merging annotations

### ISSUE THREAD

**Issue by olechnwin** [GenomeRIK/tama#100]
Hi,
This is more of a question than an issue.
I had run TAMA merge to combine my three annotations.
I can see that the resulting merged annotation does indeed combine the three annotations that I have. However, I was expecting for gene names to be in the merged annotation but it wasn't. 
Is there a way to merge the annotations including the gene names?
For example below, the last track is the merged annotation. The first track is a lifted gencode annotation. In the merged annotation below G36144 is EWSR1. How can I get an annotation that say that it is EWSR1?

![image](https://user-images.githubusercontent.com/20069067/226709638-f9c5699c-7609-454f-99d0-816e76881936.png)

I tried to run the TAMA predict pipeline [here](https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-ORF-and-NMD-predictions) but it's taking a long time and looking at the output example, it doesn't seem to be what I wanted to do. 

Do you have any recommendation on how to do this?

Thank you so much for your help.

Best,
Cen

**Comment by GenomeRIK** [comment]
Hi Cen,

I think what you are wanting is this parameter from TAMA Merge (from the wiki):
  -s S        Use gene and transcript ID from a merge source. Specify source name from filelist file here.

So if you are merging with the reference annotation you can use the source name for that annotation as from the filelist file and it will take the gene and transcript ID's from that annotation whenever they have a matching gene or transcript. 

Hope this helps!
iRichard

**Comment by olechnwin** [comment]
Hi Richard,

Thank you so much! I'll re-run TAMA Merge with the -s option.
Appreciate your help.

Cen

**Comment by olechnwin** [comment]
Hi Richard,

Sorry I have additional question. I was able to get the gene and transcript ID from a merge source. However, it seems that now the "novel" transcript disappear. As shown below, the first two tracks are the merged annotations, and the third track is missing the G50504. Is there a way to keep them?

Thanks,
Cen

**Comment by GenomeRIK** [comment]
Hi Cen,

It looks like you applied filtering somewhere. Can you send the command lines you used to get there?

Thank you,
Richard

**Comment by tky199996** [comment]
> 嗨，理查德，
> 
> 非常感谢！我将使用 -s 选项重新运行 TAMA Merge。感谢您的帮助。
> 
> 岑

How do I get Gneid?

**Comment by tky199996** [comment]
> 作者

Hello, I have been trying to use the tama -s parameter to annotate the gene name, but without success. Do you have time to help me explain how to use the -s parameter to annotate the gene name of the Gid number?
