### ISSUE TITLE
tama_collapse.py error TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by luckyvivi** [GenomeRIK/tama#105]
Hi, I'm running tama_collapse.py with python3 using this code⬇️
tama_collapse.py -b BAM -s polished.hq.bam -f GENOME.fa -x no_cap -e common_ends -p nocap_isoform > nocap_tama.collapse.log

And got an error ⬇️ 
Traceback (most recent call last):
  File "/usr/bin/tama_collapse.py", line 5095, in <module>
    sam_file_contents = sam_file_list[0].split("\n")
TypeError: a bytes-like object is required, not 'str'

could you please tell me how to fix this error, thanks in advance.

**Comment by GenomeRIK** [comment]
Hello,

Apologies but the github version of TAMA only runs on Python 2.7. If you need access to the python 3 version please email me. 

Thank you,
Richard
