### ISSUE TITLE
'dict_keys' object has no attribute 'sorted'

### ISSUE THREAD

**Issue by roybarkan2020** [GenomeRIK/tama#114]
Hi !

I am trying to run _tama collapse_ using my mapped isoseq data (sam file) with this command:
python3 tama_collapse.py -s aln_iso_hq_sort.sam -f scaffolds_final.fa -p iso_hq

I am getting an error msg: 
Traceback (most recent call last):
  File "tama_collapse.py", line 5448, in <module>
    forward_gene_start_trans_dict,forward_start_gene_list = gene_group(forward_trans_list)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tama_collapse.py", line 3528, in gene_group
    start_gene_list.sorted()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict_keys' object has no attribute 'sorted'

I had some issues with "sort()" before, so I changed "sort()" to "sorted()" (due to different Python versions).

Do you have any ideas about what could be the issue?

Many thanks!!!
Roy.

**Comment by GenomeRIK** [comment]
Hi Roy,

The public version of TAMA still runs on Python 2.7. Please use Python 2.7 to run TAMA. If you need the python 3 version please email me with info on the project and group. 

Thank you,
Richard
