### ISSUE TITLE
Issue with tama_cds_regions_bed_add.py 

### ISSUE THREAD

**Issue by roybarkan2020** [GenomeRIK/tama#120]
Hi,

I am running tama_cds_regions_bed_add.py with outputs generated from the pipeline. All outputs generated in the previous step seem to be in the same format as the manual describes but when I run tama_cds_regions_bed_add.py I am getting this error:

_Using default SJ distance of 50bp
opening blastp parse file
opening anno file
Going through sequences
Traceback (most recent call last):
  File "/home/jc748673/tama/tama_go/orf_nmd_predictions/tama_cds_regions_bed_add.py", line 193, in <module>
    cds_rel_start = trans_len_dict[trans_id] - (nuc_end + pos_adjust - 2)
KeyError: 'G1;G1.1'_

I tried using different versions of Python, etc but still getting the same error. 

Any ideas?

Many thanks!
Roy.

**Comment by Xueliang24** [comment]
I met the same problem. 
Did you solve it and share the method with me？
____
I have solved it.

**Comment by ctat41** [comment]
How did you solve it?

Never-mind, I figured it out.
