### ISSUE TITLE
About Tama collpase bed file "transcript_id"

### ISSUE THREAD

**Issue by KerenElience** [GenomeRIK/tama#121]
I notice the `${prefix}_trans_reads.bed` file contain a columns named "transcript_id", but the format is "G+{gene_count}+{trans_count}".It's not like `gtf3` file's `attributes` columns `transcript_id "ENSMUSTxxxxxx"`, could I use some tools to transform it?

**Comment by tky199996** [comment]
> 我注意到该`${prefix}_trans_reads.bed`文件包含名为“transcript_id”的列，但格式是“G+{gene_count}+{trans_count}”。它不像`gtf3`文件的`attributes`列`transcript_id "ENSMUSTxxxxxx"`，我可以使用一些工具来转换它吗？

Hello, I have the same problem, did you solve it?Can you tell me how to fix it if it is solved? Thank you.

**Comment by KerenElience** [comment]
`TAMA` can't approch it, I use python extrac `gene` from gtf, and minimap2 it.
