### ISSUE TITLE
python3.11，NameError: name 'xrange' is not defined. Did you mean: 'range'?

### ISSUE THREAD

**Issue by tky199996** [GenomeRIK/tama#124]
Hello, I am using the python version that makes 3.11, but it seems that the tama_collapse.py file does not support python 3.11 and keeps showing module errors, what should I do? Is there any tama software that can support Python 3.11? I don't know how to email you, I'm sorry

**Comment by KerenElience** [comment]
You can use `pull requests`, the python3 version. But you need edit the python script head `from * import __version__`, `from __init__ import __version__` this way is right.

<hr>
[jamestwebber:py3](https://github.com/jamestwebber/tama/tree/py3)

tama_collpase.py
```python
from __init__ import __version__
```

**Comment by tky199996** [comment]
> You can use `pull requests`, the python3 version. But you need edit the python script head `from * import __version__`, `from __init__ import __version__` this way is right.
> 
> [jamestwebber:py3](https://github.com/jamestwebber/tama/tree/py3)
> tama_collpase.py
> 
> ```python
> from __init__ import __version__
> ```
Thank you very much. I modified it according to your method and I ran it successfully, but I got two empty files, the bed file and the read.bed file. What is the problem? Thanks again for helping me!
![微信图片_20240122165124](https://github.com/GenomeRIK/tama/assets/120616828/d9baddad-49a5-44d2-b1ee-0d6d532bade1)

**Comment by tky199996** [comment]
> > You can use `pull requests`, the python3 version. But you need edit the python script head `from * import __version__`, `from __init__ import __version__` this way is right.
> > [jamestwebber:py3](https://github.com/jamestwebber/tama/tree/py3)
> > tama_collpase.py
> > ```python
> > from __init__ import __version__
> > ```
> 
> Thank you very much. I modified it according to your method and I ran it successfully, but I got two empty files, the bed file and the read.bed file. What is the problem? Thanks again for helping me! ![微信图片_20240122165124](https://private-user-images.githubusercontent.com/120616828/298519486-d9baddad-49a5-44d2-b1ee-0d6d532bade1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTM3OTgsIm5iZiI6MTcwNTkxMzQ5OCwicGF0aCI6Ii8xMjA2MTY4MjgvMjk4NTE5NDg2LWQ5YmFkZGFkLTQ5YTUtNDRkMi1iMWVlLTBkNmQ1MzJiYWRlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwODUxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2E5NTA1YTc4NWNjZmQ0NGYzZTU1MDA2MTk5MjZlYjZjNDQ2NjQxMWJmMGEwOWQyODY0ZGM0NGRlYWU2N2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DUQ7prrf2Pv64-kK09PYiooqt8A9UDRGsStqfEw4V5k)

![微信图片_20240122165735](https://github.com/GenomeRIK/tama/assets/120616828/a1a40efc-5fff-44aa-993e-f0ad855cb38a)
It looks like there is still a module error

**Comment by KerenElience** [comment]
> > > You can use `pull requests`, the python3 version. But you need edit the python script head `from * import __version__`, `from __init__ import __version__` this way is right.
> > > [jamestwebber:py3](https://github.com/jamestwebber/tama/tree/py3)
> > > tama_collpase.py
> > > ```python
> > > from __init__ import __version__
> > > ```
> > 
> > 
> > Thank you very much. I modified it according to your method and I ran it successfully, but I got two empty files, the bed file and the read.bed file. What is the problem? Thanks again for helping me! ![微信图片_20240122165124](https://private-user-images.githubusercontent.com/120616828/298519486-d9baddad-49a5-44d2-b1ee-0d6d532bade1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTM3OTgsIm5iZiI6MTcwNTkxMzQ5OCwicGF0aCI6Ii8xMjA2MTY4MjgvMjk4NTE5NDg2LWQ5YmFkZGFkLTQ5YTUtNDRkMi1iMWVlLTBkNmQ1MzJiYWRlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwODUxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2E5NTA1YTc4NWNjZmQ0NGYzZTU1MDA2MTk5MjZlYjZjNDQ2NjQxMWJmMGEwOWQyODY0ZGM0NGRlYWU2N2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DUQ7prrf2Pv64-kK09PYiooqt8A9UDRGsStqfEw4V5k)
> 
> ![微信图片_20240122165735](https://private-user-images.githubusercontent.com/120616828/298521144-a1a40efc-5fff-44aa-993e-f0ad855cb38a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTk0NTgsIm5iZiI6MTcwNTk5OTE1OCwicGF0aCI6Ii8xMjA2MTY4MjgvMjk4NTIxMTQ0LWExYTQwZWZjLTVmZmYtNDRhYS05OTNlLWYwYWQ4NTVjYjM4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwODM5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzMzZWJlM2NkMzRiODJjZGIxNjBjNzA5NTc4NDIyYTFkZTk5ZTExNmE4OGY1YjE5NGEzMGE2NTlmMjU3MTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zc20BkEhYulomk9zZfCKxpplGt9PkCAMSSTYEZw1RZA) It looks like there is still a module error

Before launching the script, you need use minimap2 to mapping your `fastq` file into `reference fasta` file, and it will generate a `sam` file. I just guess your problem caused by illegal `sam` file as input file.

**Comment by tky199996** [comment]
> > > > 您可以使用`pull requests`python3 版本。但是你需要编辑python脚本头`from * import __version__`，`from __init__ import __version__`这种方式是正确的。
> > > > [jamestwebber:py3](https://github.com/jamestwebber/tama/tree/py3) 
> > > > tama_collpase.py
> > > > ```python
> > > > from __init__ import __version__
> > > > ```
> > > 
> > > 
> > > 非常感谢。我按照你的方法修改了一下，运行成功了，但是得到了两个空文件，bed文件和read.bed文件。问题是什么？再次感谢您对我的帮助！![微信图片_20240122165124](https://private-user-images.githubusercontent.com/120616828/298519486-d9baddad-49a5-44d2-b1ee-0d6d532bade1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTM3OTgsIm5iZiI6MTcwNTkxMzQ5OCwicGF0aCI6Ii8xMjA2MTY4MjgvMjk4NTE5NDg2LWQ5YmFkZGFkLTQ5YTUtNDRkMi1iMWVlLTBkNmQ1MzJiYWRlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwODUxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2E5NTA1YTc4NWNjZmQ0NGYzZTU1MDA2MTk5MjZlYjZjNDQ2NjQxMWJmMGEwOWQyODY0ZGM0NGRlYWU2N2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DUQ7prrf2Pv64-kK09PYiooqt8A9UDRGsStqfEw4V5k)
> > 
> > 
> > ![微信图片_20240122165735](https://private-user-images.githubusercontent.com/120616828/298521144-a1a40efc-5fff-44aa-993e-f0ad855cb38a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTk0NTgsIm5iZiI6MTcwNTk5OTE1OCwicGF0aCI6Ii8xMjA2MTY4MjgvMjk4NTIxMTQ0LWExYTQwZWZjLTVmZmYtNDRhYS05OTNlLWYwYWQ4NTVjYjM4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwODM5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzMzZWJlM2NkMzRiODJjZGIxNjBjNzA5NTc4NDIyYTFkZTk5ZTExNmE4OGY1YjE5NGEzMGE2NTlmMjU3MTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zc20BkEhYulomk9zZfCKxpplGt9PkCAMSSTYEZw1RZA)看来还是有模块错误
> 
> 在启动脚本之前，您需要使用 minimap2 将您的`fastq`文件映射到`reference fasta`file，它将生成一个`sam`文件。我只是猜测你的问题是由非法`sam`文件作为输入文件引起的。
I am using the bam file obtained by pbmm2, pbmm2 align --preset ISOSEQ \
--unmapped \
--sort \
-j 20 \
--log-level INFO --log-file pbmm2.log \
../12.ref/genome.fa \
--sample T_LR \
../23.fl2flnc/T_LR.flnc.bam T_LR.bam
This is my basic parameter, through which I get the compared bam file. Do you suggest that I use the sam file as input, or how can I check whether my bam file is wrong?

**Comment by KerenElience** [comment]
这个工具对 `bam` 文件不支持，作者没有对那块维护了，你可以用 `samtools` 工具对`bam`文件进行转换

**Comment by tky199996** [comment]
> 这个工具对 `bam` 文件不支持，作者没有对那块维护了，你可以用 `samtools` 工具对`bam`文件进行转换
Oh, that’s it, thanks for your help!

**Comment by tky199996** [comment]
> > 这个工具对 `bam` 文件不支持，作者没有对那块维护了，你可以用 `samtools` 工具对`bam`文件进行转换
> > Oh, that’s it, thanks for your help!
![1](https://github.com/GenomeRIK/tama/assets/120616828/a55df27f-1f02-464d-9d9b-4e572322b28b)
Hello, I'm currently using tama_convert_bed_gtf_ensembl_no_cds.py to convert, but it looks like an error has occurred as well, thank you again for helping me, thank you!

**Comment by KerenElience** [comment]
I don't know how to fix that. But it seems like a `Class` problem, the `map` `Class` isn't exist. This may be due to the Python version, and you need to take a closer look at the source solution.

**Comment by KerenElience** [comment]
`TAMA` Tools are more suitable for data analysis with similar workflows. I recommend you use some common tools to implement your needs, such as:

1. Download the reference genome and `gtf` files from Ensembl.
2. Use `Python` or `R` to filter the `no_cds` tags of the `gtf` files and write the data into bed files.
3. Use the `seqkit grep` command and bed files in the `seqkit` tool to extract the reference genome.
4. Use `pbmm2` or `minimap2` tools to align your sequencing sequences with the extracted reference genome file.
5. You can further use `paftools.js sam2paf` to convert the `sam` file into a more readable `paf` file.

Good luck!

**Comment by tky199996** [comment]
> `TAMA` Tools are more suitable for data analysis with similar workflows. I recommend you use some common tools to implement your needs, such as:
> 
> 1. Download the reference genome and `gtf` files from Ensembl.
> 2. Use `Python` or `R` to filter the `no_cds` tags of the `gtf` files and write the data into bed files.
> 3. Use the `seqkit grep` command and bed files in the `seqkit` tool to extract the reference genome.
> 4. Use `pbmm2` or `minimap2` tools to align your sequencing sequences with the extracted reference genome file.
> 5. You can further use `paftools.js sam2paf` to convert the `sam` file into a more readable `paf` file.
> 
> Good luck!

Thank you for your help, I will try the process you provided.

**Comment by tky199996** [comment]
> `TAMA`工具更适合具有类似工作流程的数据分析。我建议您使用一些常用工具来实现您的需求，例如：
> 
> 1. 从 Ensembl下载参考基因组和`gtf`文件。
> 2. 使用`Python`或`R`过滤文件`no_cds`的标签`gtf`并将数据写入bed文件。
> 3. 使用工具`seqkit grep`中的命令和bed文件`seqkit`提取参考基因组。
> 4. 使用`pbmm2`或`minimap2`工具将测序序列与提取的参考基因组文件进行比对。
> 5. 您可以进一步使用`paftools.js sam2paf`将`sam`文件转换为更具可读性的`paf`文件。
> 
> 祝你好运！
Thank you, I think it may be a problem with the python version. When using the tama_collapse.py script, you should use the python3.11 version and need to modify it according to the method you provided before. When using the tama_convert_bed_gtf_ensembl_no_cds.py script, you still need to switch to python2.7 version for conversion. Thanks for your help, thank you again!

**Comment by tky199996** [comment]
> `TAMA`工具更适合具有类似工作流程的数据分析。我建议您使用一些常用工具来实现您的需求，例如：
> 
> 1. 从 Ensembl下载参考基因组和`gtf`文件。
> 2. 使用`Python`或`R`过滤文件`no_cds`的标签`gtf`并将数据写入bed文件。
> 3. 使用工具`seqkit grep`中的命令和bed文件`seqkit`提取参考基因组。
> 4. 使用`pbmm2`或`minimap2`工具将测序序列与提取的参考基因组文件进行比对。
> 5. 您可以进一步使用`paftools.js sam2paf`将`sam`文件转换为更具可读性的`paf`文件。
> 
> 祝你好运！

Hello, when I run tama_merge.py using python3.11, the following error occurs. How can I solve it?
![截屏3](https://github.com/GenomeRIK/tama/assets/120616828/2c0f427e-e220-4304-b73c-6abb36dc9d50)
