### ISSUE TITLE
tama_merge.py

### ISSUE THREAD

**Issue by tky199996** [GenomeRIK/tama#127]
When I run tama_merge.py using python3.11, the following error occurred. How can I solve it?
![截屏3](https://github.com/GenomeRIK/tama/assets/120616828/7dd77786-6486-4641-82eb-cc125c4354c9)

**Comment by tky199996** [comment]
![Uploading 截屏3.png…]()

**Comment by GenomeRIK** [comment]
Hello,

This version of TAMA can only be run with Python 2.7.

Thank you,
Richard

**Comment by tky199996** [comment]
> 你好，
> 
> 此版本的 TAMA 只能使用 Python 2.7 运行。
> 
> 谢谢你， 理查德

Hi, thanks for the recovery, when I try to run with python2.7 it shows module error.
![Uploading 恢复.png…]()

**Comment by tky199996** [comment]
> 你好，
> 
> 此版本的 TAMA 只能使用 Python 2.7 运行。
> 
> 谢谢你， 理查德

![恢复](https://github.com/GenomeRIK/tama/assets/120616828/3fca05a1-5db2-44e6-a481-8029284cc568)
