### ISSUE TITLE
tama_merge.py

### ISSUE THREAD

**Issue by tky199996** [GenomeRIK/tama#128]
When I run tama_merge.py using python2.7, a module error is displayed. How can I adjust it?
![Uploading 恢复.png…]()

**Comment by tky199996** [comment]
![Uploading 恢复.png…]()

**Comment by GenomeRIK** [comment]
Hello,

You need to have the biopython module to run it. 

Thank you,
Richard

**Comment by tky199996** [comment]
> Hello,
> 
> You need to have the biopython module to run it.
> 
> Thank you, Richard

Hello, when I run tama_merge.py using python3, it prompts me the following error, when I run using python2.7, it prompts me module error, so how can I solve it, I prefer to run this script using python3, because it seems Changing the file format will be easier than adjusting the script. Here are the problems I encountered and the file format.
![微信图片_20240226152908](https://github.com/GenomeRIK/tama/assets/120616828/6a23ae69-0581-4825-b7c8-78df16f68db5)
![微信图片_20240226152949](https://github.com/GenomeRIK/tama/assets/120616828/c11bf132-82f2-48b4-b966-4b2f25168091)

**Comment by GenomeRIK** [comment]
TAMA can only be run with Python 2.7. You will need to install the python 2.7 module for Biopython to run.

**Comment by tky199996** [comment]
> TAMA 只能使用 Python 2.7 运行。您需要安装 python 2.7 模块才能运行 Biopython。

Hello, I try to run with python2.7 but it shows module error
![Uploading 微信图片_20240226205706.png…]()

**Comment by tky199996** [comment]
> TAMA can only be run with Python 2.7. You will need to install the python 2.7 module for Biopython to run.
![1708952502404](https://github.com/GenomeRIK/tama/assets/120616828/41a01863-2894-4e13-9c9e-99d11de39a78)
When I installed the biopython module, it prompted me that python2.7 no longer supports the biopython module.
