### ISSUE TITLE
tama_collapse.py，gene_id

### ISSUE THREAD

**Issue by tky199996** [GenomeRIK/tama#129]
Hello, when I ran tama_collapse.py, I got the bed file, and then I converted the bed file into a gtf file. What I am confused about is that my gene_id is in the form of G1, G2, G3, etc., in my subsequent use When suppa2 performs alternative splicing event analysis, my gene_id is still in this form, but I want to know the specific gene names. How do I know the specific gene names represented by these gene_ids? Thank you for your help.
![Uploading gene.png…]()

**Comment by GenomeRIK** [comment]
You can use TAMA Merge to link the arbitrary Gene ID's to an annotation of choice. Using the source naming parameter.

**Comment by tky199996** [comment]
> You can use TAMA Merge to link the arbitrary Gene ID's to an annotation of choice. Using the source naming parameter.

hello,Is there any specific command to help me complete this step? I don’t know how to complete it. Thank you for your help.
