### ISSUE TITLE
Meaning of variant type 'S'

### ISSUE THREAD

**Issue by skeffington** [GenomeRIK/tama#16]
Many thanks for this wonderful program - it's saved our project!

I just have a query about the *variants.txt output of TAMA merge. I can't work out what variant type 'S' is. It generally seems to happen towards the end of reads, so something to do with soft-clipping??

For example, if I look at this line from the variants file
```{}
000000F_arrow   666056  S       C       7       158     P:86414:216:840:60,A:16022:42:1132:60,P:47592:827:1234:60,A:17843:3:1152:46,P:67241:39:1057:60,B:79276:31:507:60,P:75873:21:936:60
```
And look at this position on the genome browser, then the position 666056 is the penultimate base of read P:86414:216:840:60. The read sequence from 666055-666057 is CAC and the genome sequence is also CAC. So what is the variant that's being reported?

Any insights would be much appreciated!
Alastair

**Comment by GenomeRIK** [comment]
Hi Alastair,

Really put a smile on my face to hear that the software is helping people!

The variant type "S" should be soft clipping but as you pointed out, it is strange if the reads and the genome have the same sequence at that locus. 

Do you mind copy/pasting the pre-mapped read sequence for 3 of the reads (P:86414:216:840:60,A:16022:42:1132:60,P:47592:827:1234:60) from the read support for that variant? And a slice of the genome for 000000F_arrow:666040-666070?

Could you also copy/paste the lines for those 3 reads (P:86414:216:840:60,A:16022:42:1132:60,P:47592:827:1234:60) from the "prefix_read.txt" file?

Thank you,
Richard

**Comment by skeffington** [comment]
Hi Richard,

Thanks for your swift reply.

Now I know it's to do with soft-clipping I had another look and each of these reads has a C that is soft clipped where there is an A in the genome. It's just a bit odd that the position for the variant is given as 666056, whereas the clipped base would align to 666058. When I look at other variant types the position indicated in the variants file makes sense.

The data you ask for are below.

Thanks!
Alastair


```{}
>P:86414:216:840:60
TACTCGATCGCCTCGTCGCGCTACGGCGACGACATGACGGGCACGACGACGACCCTCTGCGTGCGCCGCGCCACCTACTGGTGCCCCGAGCTCAAGGCGGACGACCCCGCCAAGAAGGGCGTGTGCTCCAACTATTTGTGCGACTCCAAGCCAGGCGACGACGTCAAGCTGACCGGCCCGTCGGGCAAGGTGATGCTCATCCCGGAGAAGGACCCGAACGTCGACCTCATCATGGTCGCCACCGGCACCGGCATCGCGCCGTACCGCTCCTTCATCCGCCGCCTCTTCGTCGAGAAGACGCCCTTCGGCGAGGCGTACACCAAGGGGACCGGCCAGGCCTGGCTCTTCCTCGGCGTCGCCAACAGCGACGCGCTGCTGTACGACGACGAGTGGCAGGAGGTCCTCAAGAAGTACCCCGACAACTTCCGGCTGGACTACGCCCTCTCGCGCGAGCAGAAGAACAAGGACGGCGGCAAGATGTACATCCAGGACAAGGTCGCGGAGTACTCGGACGAGATCTTCTCCAAGATGGACAACGGCGCGCACATGTACTTTTGCGGCCTCAAGGGCATGATGCCCGGCATCACCGAGATGCTCGAGGGCGTGTGCAAGGACAAGGGGCTCGTGTGGGAGGACAAGCTCAGCGAGTGGAAAAAGGCGGGCCAGTGGCACGTCGAGGTCTACTAGGCGCTTATGCGGGGCGGCTCTGCATGCGACCCGCACGGCGCGGAATCCCTCGGCGGCACTCTCTCTGTGCGCTCGCGGCCCCGAGGGGTTGTGTACATCTGTGACGGGGAACTCGGACAACGTAAATCCTAAATAATCAGTGTGTGGAACACC
>A:16022:42:1132:60
CTCAGCTTCGGGGATTCTCCCACACAGCTATGCTCGCGGTGACCTCTGCCTTCACCTCTGGGGCGGCGCTCGTCGCGCCCACAGCGCATGCCAGCCGCGCGTCGGTGCAGATGGGCATCATTGACGGTGTGAAGAACCTGCTCGGCAAGAAGCAGGACTTCCTCGAGGCGGAGCCGTACTGGGACCAGTCGACCATCCCGGTCAACACGTACAAGAACAAGGCGCCCTTCACCGGCAAGATCGTCTCGACCAAGCGCATTGTCGGCCCGGAGGCCACCGGCGAGACTTGCGACATCGTCATCGGCCACGAGGGCAAGATGCCGTACTGGGAGGGCCAGTCGTACGGCGTCATCCCGCCGGGCACCAACCCGAAGAACGGCAAGCCAAACTCGGTCCGCCTCTACTCGATCGCCTCGTCGCGCTACGGCGACGACATGACGGGCACGACGACGACCTCAAGCTGACCGGCCCGTCGGGCAAGGTGATGCTCATCCCGGAGAAGGACCCGAACGTCGACCTCATCATGGTCGCCACCGGCACCGGCATCGCGCCGTACCGCTCCTTCATCCGCCGCCTCTTCGTCGAGAAGACGCCCTTCGGCGAGGCGTACACCAAGGGGACCGGCCAGGCCTGGCTCTTCCTCGGCGTCGCCAACAGCGACGCGCTGCTGTACGACGACGAGTGGCAGGAGGTCCTCAAGAAGTACCCCGACAACTTCCGGCTGGACTACGCCCTCTCGCGCGAGCAGAAGAACAAGGACGGCGGCAAGATGTACATCCAGGACAAGGTCGCGGAGTACTCGGACGAGATCTTCTCCAAGATGGACAACGGCGCGCACATGTACTTTTGCGGCCTCAAGGGCATGATGCCCGGCATCACCGAGATGCTCGAGGGCGTGTGCAAGGACAAGGGGCTCGTGTGGGAGGACAAGCTCAGCGAGTGGAAAAAGGCGGGCCAGTGGCACGTCGAGGTCTACTAGGCGCTTATGCGGGGCGGCTCTGCATGCGACCCGCACGGCGCGGAATCCCTCGGCGGCACTCTCTCTGTGCGCTCGCGGCCCCGAGGGGTTGTGTACATCTGTGACGGGGAACTCGGACAACGTAAATCCTAAATAATCAGTGTGTGGAACACC
>A:17843:3:1152:46
CAGCTTCGGGGATTCTCCCACACAGCTATGCTCGCGGTGACCTCTGCCTTCACCTCTGGGGCGGCGCTCGTCGCGCCCACAGCGCATGCCAGCCGCGCGTCGGTGCAGATGGGCATCATTGACGGTGTGAAGAACCTGCTCGGCAAGAAGCAGGACTTCCTCGAGGCGGAGCCGTGCTGGGACCAGTCGACCATCCCGGTCAACACGTACAAGAACAAGGCGCCCTTCACCGGCAAGATCGTCTCGACCAAGCGCATTGTCGGCCCGGAGGCCACCGGCGAGACTTGCGACATCGTCATCGGCCACGAGGGCAAGATGCCGTACTGGGAGGGCCAGTCGTACGGCGTCATCCCGCCGGGCACCAACCCGAAGAACGGCAAGCCAAACTCGGTCCGCCTCTACTCGATCGCCGCGCCGCGCCGCGCCAAGAAGGGCGTGTGCTCCAACTATTTGTGCGACTCCAAGCCAGGCGACGACGTCAAGCTGACCGGCCCGTCGGGCAAGGTGATGCTCATCCCGGAGAAGGACCCGAACGTCGACCTCATCATGGTCGCCACCGGCACCGGCATCGCGCCGTACCGCTCCTTCATCCGCCGCCTCTTCGTCGAGAAGACGCCCTTCGGCGAGGCGTACACCAAGGGGACCGGCCAGGCCTGGCTCTTCCTCGGCGTCGCCAACAGCGACGCGCTGCTGTACGACGACGAGTGGCAGGAGGTCCTCAAGAAGTACCCCGACAACTTCCGGCTGGACTACGCCCTCTCGCGCGAGCAGAAGAACAAGGACGGCGGCAAGATGTACATCCAGGACAAGGTCGCGGAGTACTCGGACGAGATCTTCTCCAAGATGGACAACGGCGCGCACATGTACTTTTGCGGCCTCAAGGGCATGATGCCCGGCATCACCGAGATGCTCGAGGGCGTGTGCAAGGACAAGGGGCTCGTGTGGGAGGACAAGCTCAGCGAGTGGAAAAAGGCGGGCCAGTGGCACGTCGAGGTCTACTAGGCGCTTATGCGGGGCGGCTCTGCATGCGACCCGCACGGCGCGGAATCCCTCGGCGGCACTCTCTCTGTGCGCTCGCGGCCCCGAGGGGTTGTGTACATCTGTGACGGGGAACTCGGACAACGTAAATCCTAAATCAGTGTGTGGAACACC

>000000F_arrow:666040-666070
AATCAGTGTGTGGAACACAGTCTGTGCTCCC


P:86414:216:840:60      forward_strand  accepted        99.88   99.88   0;1;0;0;0       840     25M88N71M182N743M1S
A:16022:42:1132:60      forward_strand  accepted        99.91   99.91   0;1;0;0;0       1132    61M114N33M261N218M304N114M88N29M291N676M1S
A:17843:3:1152:46       forward_strand  accepted        99.91   99.31   0;1;0;3;4       1152    59M114N33M261N218M304N109M354N714M3D18M1S
```

**Comment by GenomeRIK** [comment]
Hi Alastair,

Ok I see the problem now. There is a bug for identifying the genome coordinate of soft clip variants that occur at the end of the read mapping. Basically, I stopped counting the coordinates after the last mapped nucleotide (this is in 0 base bed format).

So in your case the coordinate should have been:
000000F_arrow   666057

It is not 666058, because this is bed 0 base. It is confusing and I am well aware!

I am going to fix this bug and upload the new version to the repo. I'll send another comment when I have completed the fix. 

Thank you for finding this issue and please let me know if you see anything else weird. Also if there are any additional information you would like from the output files let me know and I can see if I can implement it. 

Thank you,
Richard

**Comment by GenomeRIK** [comment]
Hi Alastair,

I have just fixed the bug and pushed the updated version of TAMA Collapse to the repo.

You can now re-clone the repo and run again and the S variant positions should be fixed. 

Please let me know if it works for you. 

Thank you,
Richard

**Comment by skeffington** [comment]
Hi Richard,
Looks good to me.
Thanks again!
Alastair

**Comment by GenomeRIK** [comment]
Excellent! Thank you for helping me fix this bug. I'll close the issue now. 

Cheers,
Richard
