### ISSUE TITLE
how does TAMA do variant calling?

### ISSUE THREAD

**Issue by skeffington** [GenomeRIK/tama#17]
Hi again - I'm afraid I have another query.

I was wondering if you can provide more details of how TAMA collapse does its variant calling? In particular, when I view the reads in the igv I often see variants that are not represented the *variants.txt file. For example, at one locus there are 12 reads contributing to a single TAMA model, ranging from 180 to 960 bp, most of which have no clipping. A couple have 1-2 bp soft clipping and one read has 40 bp soft clipping. Otherwise they match the genome perfectly except a couple 2 bp of insertions. These are at 5 locations, 4 of which are consigned to single reads, but one of which is in 4 / 12 reads. None of these 5 insertions are reported in the variants file, so what is the logic behind the variant calling?

This is important to me because I'm working with a non-model alga species and I'm interested in having as accurate as possible predicted protein sequences. Our PacBio genome is about 40x coverage and we have a lot of isoseq data which we're using to build the gene models. Both sets of data still have PacBio errors. To make things more complicated, the genome is diploid, with moderate heterozygosity, and there are some parts of the genome where the two haplotypes cannot be resolved by Falcon-unzip / Purge Haplotigs. I've been trying to use the *variants.txt file to help me decide whether to use sequence data from the genome or the isoseq data for building the a final CDS at different locations. For example, if ```R = 'count' / 'cov_count'```, then high R might indicate that the variant is due to a PacBio error in the genome; low R a PacBio error in the isoseq read; and R= 0.5 may be due to the genomic locus still being a mixture of two alleles resulting in isoseq from both alleles mapping at one locus. I'm then using this information to build the final CDS.

Any help you can give would be much appreciated!

Many thanks,
Alastair

**Comment by GenomeRIK** [comment]
Hi Alastair,

You have good queries! Keep them coming!

Right now TAMA Collapse calls variants by looking at the coverage of all accepted mapped reads at any given locus. If there are 5 or more reads supporting the variant, then it is logged in the variant file.

I can easily add a feature to allow users to change the threshold but so far no one seems to have used this feature. 

I am not sure I completely understand the example you are describing. Could you include an image of this example in the genome browser?

Thank you,
Richard

**Comment by skeffington** [comment]
Hi Richard,

Great - thanks for your answer. The threshold explains what I was seeing and is actually quite convinient for this particular data set. Sorry about the confusing example, I just wasn't sure what parameter was relevant.

Thanks again!
Alastair

**Comment by GenomeRIK** [comment]
Hi Alastair,

Ok I'm glad I could help. Let me know if you have any more questions or issues. I am going to close this thread now. Feel free to open another one if you have another question. 

Also I will update the wiki to explain the information about the variant calling. 

Thank you,
Richard
