### ISSUE TITLE
Can TAMA Merge preserve read counts from different samples?

### ISSUE THREAD

**Issue by jackhump** [GenomeRIK/tama#27]
Hi Richard,

Thank you for creating these really useful tools for long read RNA-seq analysis!

I'm particularly interested in comparing technical replicability between different Isoseq runs. I have both technical replicates from the same sample and biological replicates from different samples. I'd like to use TAMA to merge the different transcript models from each sample and then compare the abundances (read counts) between samples. Is this currently possible with TAMA Merge? 

I've been exploring the chaining functions created by Liz Tseng as well and I can see that it's quite a difficult problem to match isoforms across datasets and it doesn't always seem to work as expected.

**Comment by GenomeRIK** [comment]
Hi Jack,

Thanks for using TAMA!

As for your question about getting abundances from each sample with TAMA Merge, you can definitely do this! You just need to use "tama_read_support_levels.py" which you can find instructions for using here:
https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Read-Support

So you just need to have each sample separate in your TAMA Merge run (ie do not merge samples prior to the TAMA Merge run) and then use tama_read_support_levels.py to generate read_support files working your way up from the collapsing step. 

At the end you will get a read support file which shows the read IDs and sample IDs for each transcript model. At this time it does not provide a field with a summary of the number of reads per sample for each transcript but you can extrapolate this from the last column which shows each read id and source sample for each transcript.

However, it is very easy for me to add the summary reads per sample per transcript output if you want it. Just let me know and I will add another file output which gives that information. 

Cheers,
Richard

**Comment by jackhump** [comment]
Thanks Richard for your quick response! I'll look into this and let you know how I get on.

Best wishes,

Jack

**Comment by GenomeRIK** [comment]
Hi Jack,

Just checking to see if your TAMA runs were ok? I can make changes to outputs if you need them. 

If everything is ok, I will close this Issue thread. 

Thank you,
Richard

**Comment by jackhump** [comment]
Hi Richard, I'm still yet to run this as we've been held up waiting for data. 

Feel free to close this issue and I'll contact you when I eventually get to try this out.

best wishes,

Jack

**Comment by GenomeRIK** [comment]
Hi Jack,

Ok I will close this issue for now but I can open it up later if need be. Feel free to message me if you have any questions about processing the long read data. 

Cheers,
Richard

**Comment by SziKayLeung** [comment]
Hello Richard, 

Thank you reopening the thread and apologies - will reopen in future but glad this request came through. 

Perhaps I'm missing something, but this is the output that I receive from the tama_read_support_levels.py, where the source of each transcript is in the support line. 
![image](https://user-images.githubusercontent.com/33493350/137132652-a064d854-c411-4a5c-8869-69e06271b8d0.png)

However, I was wondering whether it would be possible to create a separate output file tabulating the number of reads from each sample for each transcript (TAMA defined): 
![image](https://user-images.githubusercontent.com/33493350/137133173-dfb68090-6f82-44c6-a481-d9ab9074725b.png)
Each column is a sample. So for example in G4.2, there were 6 merged transcripts, 3 of which came from Batch3BC4. 

Let me know if this is something that it is easy and possible for you to create, 

Thank you, 
Szi Kay

**Comment by SziKayLeung** [comment]
Hello Richard, 

I've been trying to  parse the information from the matrix, but unfortunately I have thousands of ONT reads and my script keeps failing to finish (memory issues). It would therefore be great if you have time to do this. 

Thank you, 
Szi Kay

**Comment by GenomeRIK** [comment]
Hi Szi Kay,

Sorry I didn't have time back then to work on this. I am guessing you have moved on but if you still need this functionality please let me know.

Thank you,
Richard
