### ISSUE TITLE
Error: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by aksenia** [GenomeRIK/tama#28]
Hi Richard, 

I am getting an error when running TAMA Collapse on public data (unpolished FLNC): 

`Traceback (most recent call last):
  File "/home/bin/tama/tama_collapse.py", line 4447, in <module>
    map_seq_length = mapped_seq_length(cigar)
  File "/home/bin/tama/tama_collapse.py", line 360, in mapped_seq_length
    map_seq_length = map_seq_length + int(cig_dig_list[i])
ValueError: invalid literal for int() with base 10: '11=1'`

Any advice? I used minimap2 with recommended flags and it always worked for me before. 
Thanks! 
Ksenia

**Comment by GenomeRIK** [comment]
Hi Ksenia!

I hope you are doing well! This is an interesting issue. 

Can you share the Minimap2 version you used and the parameters you used for mapping?

Can you also run this bash script for  your SAM file?
cat ${samfile} | grep -v "^@" | awk -F "\t" '{print $1"\t"$6}' | grep "11=1" | head

I think for some reason you are getting "=" symbols in your CIGAR string. Minimap2 did not used to do this with RNA sequence mapping mode so maybe this is a new behavior in the latest version. If this is the issue I can account for the "=" symbol in TAMA Collapse and update. However, I would like to check that this isn't happening for another reason. 

Thank you,
Richard

**Comment by aksenia** [comment]
It is all good - thanks! Hope same with you. 

So here is my minimap2 version: 2.17-r941
And the output of the command above (a couple of lines): 
`m54006_170729_232022/7733403/ccs	9=1D11=1X22=1D26=1I9=15940N14=1I25=1I12=1D12=1I9=2I21=1I6=1D5=1D7=1I17=1I30=1D19=2I2=1I18=1I8=1I27=1I42=1I9=1X5=1X20=1D9=1D26=1I26=1X3=1I15=1X37=1I6=1D27=1I42=1I4=2X12=1I1=1X38=2X29=2X4=1D80=1I7=2I4=1I3=1I6=1X8=1I2=2I26=1D8=1X12=1I35=1D7=1I2=1X33=2I34=1X88=1D17=1I13=1I38=1I22=1D40=2I4=1X15=1I33=2X8=2I28=1D6=1D4=1I10=1I7=1X46=1I6=1I2=1I48=1I4=2X12=1I15=2I5=2I4=1D5=1I11=1X9=1I3=1I13=1D50=1D4=1D30=1X59=1X16=1D6=1D7=1I63=1I27=1D5=3I28=1I13=1I21=1I9=2I17=2X1=1X5=2I13=1I28=1I17=1I5=1X39=1I13=1D2=1X8=1I5=1D56=1D15=1I43=1D83=1D19=1X23=1D4=1I25=1X3=1I11=1D11=1D5=1D27=1D21=1I14=1I21=1I49=1I38=1I3=1X13=3I14=1I5=1I6=1I36=1I14=1D4=1I17=1X8=1D27=2X19=1I8=1I7=1I30=1D16=1I19=1I14=1X3=1D11=2I1=1D24=1I7=3I9=1I18=1I3=12728N6=1D13=1I27=1I9=1I22=1D13=1X19=1X3=1I54=1D9=1I1=1X3=1295N6=1I10=1D13=1D2=2X9=1D23=1I56=
m54006_170729_232022/9568940/ccs	5S31=1D19=15940N63=1D70=1D69=1X2=1X34=1D10=1D34=1D22=1D57=1D5=1X27=1D14=1D24=1D24=1D46=1D3=1D9=1X22=1X164=1D12=1D15=1D39=1D17=1X62=1D18=1D15=1D24=1D19=1X12=1D121=1D7=1D99=1D19=1D86=1D38=1D27=1D66=1X49=1D7=2D7=1D56=1D37=1D4=1D83=1D76=1D13=1X6=1D24=1D46=1X31=1D5=1D21=1D93=1D29=1D20=1D62=1D18=2D51=1X8=1D63=1D59=1X20=1X6=1D15=1D9=1D47=1D42=1D16=1D11=1X2=1X105=1D35=1D26=1D25=1D20=1D18=12728N5=2D23=2D28=1D31=1X14=1I78=1295N41=1D10=1D5=1D26=1D5=1D55=1D28=1X13=1X7=1D5=1X16=1D4=1X55=1D59=3I23=1X8=1X5=1X33=1D16=1D43=1X48=1D22=1X11=1D82=1I16=1D29=4D35=1D52=1D39=1D11=1X8=1D9=1X6=1X25=1D2=1D79=1X14=1D61=1D12=1D3=1X15=1D13=1X66=17D8=1D14=1D2=1X18=1D91=1X45=1I2=1D2=1D26=1X57=1D78=1X11=1D4=1X14=1D11=1D16=1I27=1D7=1X5=1D11=1D98=1D16=1D10=1X27=11I1=1X1=1X1=1X2=1X1=1X12=1I74=1X40=1D46=1D11=1X97=1D23=1D14=1D34=1D9=1D38=1D5=1D90=1D36=1D61=1D76=1X18=1X59=1X23=1D3=1X3=1D63=1D42=1D6=1D15=1I82=1D49=1D28=`

**Comment by GenomeRIK** [comment]
Hi Ksenia,

Ok it looks like this is happening because you used the "-a" parameter. So instead of using "M" in the CIGAR line, Minimap2 is using the "=" and "X" in the CIGAR line. 

So you could either re-map without the "-a" or I could add this feature to TAMA Collapse. I might not be able to work on this until the weekend if timing is an issue. 

Which would you prefer?

Cheers,
Richard

**Comment by aksenia** [comment]
Hi Richard, 

Thanks for pointing this out! 
No worries, I will re-map the data. 
In case if other users of your tool run into the same, they hopefully can google this issue.  
Please, feel free to close the issue. 

Best,
Ksenia

**Comment by GenomeRIK** [comment]
Thanks for posting this issue! I am sure it will be helpful for others! 

I will try to add this CIGAR style option for TAMA collapse in the future.

PS I am going to speed up TAMA Collapse quite a bit in the next major update.
