### ISSUE TITLE
issue with format converter tama_format_gtf_to_bed12_ncbi.py

### ISSUE THREAD

**Issue by yuanyuan929** [GenomeRIK/tama#30]
Hi Richard,

I see that you have fixed the issue already - thanks for the quick response to my email! I am just leaving this comment here in case other users using the older version of the script run into the same issue.

The issue was that columns 2 and 3 of the output bed file were showing the start and end coordinates of the first exon of a transcript, instead of the transcript start and end; and for transcripts on the reverse strand, exon relative starts in column 12 were negative.

Thanks for making the tools :)

Yuanyuan

**Comment by GenomeRIK** [comment]
Hi Yuanyuan,

Thank you for finding this issue. 

Cheers,
Richard
