### ISSUE TITLE
tama merge -s error

### ISSUE THREAD

**Issue by yuanyuan929** [GenomeRIK/tama#31]
Hi Richard,

I ran into an error when running tama merge using a refseq annotation file as source for gene/transcript ID with the -s option.

Traceback (most recent call last):
  File "/project/devil_lp18/yuanyuan/tama/tama_merge.py", line 3595, in <module>
    total_gene_count = process_trans_group(group_trans_list,total_gene_count)
  File "/project/devil_lp18/yuanyuan/tama/tama_merge.py", line 3408, in process_trans_group
    this_source_gene_id = source_trans_gene_dict[this_source_name][this_source_trans_id]##################################################
KeyError: 'XM'

It probably has something to do with refseq's transcript ID format, which contains an underscore between the accession prefix and number?

Thanks,
Yuanyuan

**Comment by GenomeRIK** [comment]
Hi Yuanyuan,

Thanks for pointing this out! Yeah I don't usually work with NCBI annotations so I need to account for their method of ID formatting. I will try to make the fix tonight. 

I'll post again when this has been fixed. 

Cheers,
Richard

**Comment by GenomeRIK** [comment]
Hi Yuanyuan,

Ok I think I fixed the problem. Can you reclone and let me know if it works for you now?

Thank you,
Richard

**Comment by yuanyuan929** [comment]
Great, yes it works now. I like this new feature by the way!

Thanks,
Yuanyuan

**Comment by GenomeRIK** [comment]
Hi Yuanyuan,

Glad it works now. This got me thinking that I should expand the feature to accept multiple source inputs so you can test Ensembl vs NCBI vs Iso-Seq. I'll close this issue now but I'll see about expanding the feature soon. 

Thank you,
Richard
