### ISSUE TITLE
error using bam file with tama_collapse

### ISSUE THREAD

**Issue by yuanyuan929** [GenomeRIK/tama#32]
Hi Richard,

There seems to be an issue with tama_collapse when bam file is provided as input file with flag -b. Please see below for the full output lines. Would you mind fixing this in the next update?

Thanks,
Yuanyuan

tc_version_date_2020_07_18
Sam file is missing
Default capped flag will be used: Capped
Default collapse exon ends flag will be used: common_ends
Default coverage: 99
Default identity: 85
Default identity calculation method: ident_cov
Default 5 prime threshold: 10
Default exon/splice junction threshold: 10
Default 3 prime threshold: 10
Default duplicate merge flag: merge_dup
Default splice junction priority: no_priority
Default splice junction error threshold: 10
Default splice junction local density error threshold: 1000
Default simple error symbol for matches is the underscore "_" .
Using BAM format for reading in.
Default log output on
Default run mode original
Default 5 read threshold
Please try again with complete arguments
Traceback (most recent call last):
  File "/project/devil_lp18/yuanyuan//tama/tama_collapse.py", line 207, in <module>
    sam_file = opts.s[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by GenomeRIK** [comment]
Hi Yuanyuan,

Can you send me the whole command line used to run? You can change the file names to hide any sensitive information.

Thank you,
Richard

**Comment by yuanyuan929** [comment]
Hi Richard,

Sorry, problem solved! A colleague of mine mentioned this issue to me yesterday, and I did not check the command lines used carefully before reporting it. I just noticed that one of the command lines used was missing the argument BAM for -b, and in another one the bam file was directly provided to -b instead of -s.

Sorry about the confusion!

Yuanyuan
