### ISSUE TITLE
ImportError: No module named pysam

### ISSUE THREAD

**Issue by yichangyu** [GenomeRIK/tama#39]
Dear TAMA developer:

Thanks for developing TAMA. 

I got an error when I run `tama_collapse.py`, saying `ImportError: No module named pysam`. I fixed it by install `pysam` package using conda. Could you please take a look to see this a general issue?

Thanks
Changyu

**Comment by GenomeRIK** [comment]
Hello Changyu,

Thank you for using TAMA and for pointing this out. I have added the need to install pysam into the wiki. You only need pysam if you are using a BAM instead SAM input for TAMA Collapse. But it looks like you figured it out anyway. 

Cheers,
Richard
