### ISSUE TITLE
how to predict NMD

### ISSUE THREAD

**Issue by Sisov** [GenomeRIK/tama#4]
Dear author:
Can you explain how to predict the NMDs ? Is there have a  criterion to predict ,besides,how to explain the results 
![image](https://user-images.githubusercontent.com/22792569/40155848-793b2916-59c8-11e8-948e-26b88a6d61ce.png)

**Comment by GenomeRIK** [comment]
Hi Sisov,  good question! I still need to add more information to the wiki page to explain this but basically I am just predicting NMDs by looking at transcripts which are predicted to be protein coding but have a stop codon at least 50bp upstream of the last splice junction. You can find more information about this from my paper where I used the same algorithm:
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-017-3691-9

**Comment by GenomeRIK** [comment]
Hi Sisov, I have just updated the wiki to include a description of the output. I am closing this issue now. Thank you!
