### ISSUE TITLE
Hidden characters in shebang

### ISSUE THREAD

**Issue by ebioman** [GenomeRIK/tama#46]
I found a little bug in the python scripts `tama_collapse.py` and `tama_merge.py`,
When executing them directly I had errors such as 

```bash 
./tama_collapse.py
/usr/bin/env: ‘python\r’: No such file or directory
```
Which I did not understand as the header looks on the first glance correct:

```
#!/usr/bin/env python
```
and the execution via `python2 tama_collapse.py` worked correctly.
Upon inspection with `od -c` I found though for both - merge and collapse - the following hidden characters:

```
0000000   #   !   /   u   s   r   /   b   i   n   /   e   n   v       p
0000020   y   t   h   o   n  \r  \n  \r  \n
0000031
```
replacing this with `sed  's|\r||' tama_collapse.py ` seems to fix that behaviour

**Comment by GenomeRIK** [comment]
Hi thanks for pointing this out. Can you let me know how you actually put TAMA on your system? Did you use git clone or did you directly download the scripts? Or some other way?

Cheers,
Richard

**Comment by ebioman** [comment]
Hi
I used git clone.
Thanks
