### ISSUE TITLE
tama_merge filelist error

### ISSUE THREAD

**Issue by caiobrunharo** [GenomeRIK/tama#48]
Hi

I am trying to assemble a transcriptome for my non-model plant species. I would like to perform a RNA-seq study afterwards. I multiplexed 2 samples in a Sequel II 8M, and I was able to conclude the isoseq3 + cogent pipelines. These 2 samples are from different plant individuals, but both from leaf tissue, so I think it makes sense to merge them first as a single transcriptome before I conduct the RNA-seq study.

I saw your presentation at one of the UC Davis workshops where you present about TAMA, and I think tama_merge is the tool I am looking for to merge the two assembled transcriptomes.

I am getting the following error when using tama_merge.py:

------------------------------------------------------------------
(anaCogent) [Linux@helens-vm1 TAMA_Merge]$ python ../tama/tama_merge.py -f filelist.txt -p merged_transcriptome -d merge_dup
Default collapse exon ends flag will be used: common_ends
Default 5 prime threshold: 20
Default exon end/splice junction threshold: 10
Default 3 prime threshold: 20
Default source ID merge flag: no_source_id
Default CDS merge flag: no_cds
opening file list
Incorrect seq types given in filelist file. Please use capped or  no_cap

-------------------------------------------------------------------

And this is how my filelist looks like:

file_name	cap_flag	merge_priority(start,junctions,end)	source_name
hq_transcripts.fasta.no5merge.collapsed.filtered_G10.bed	capped	1,1,1	caplib
hq_transcripts.fasta.no5merge.collapsed.filtered_P1.bed	no_cap	2,1,1	nocaplib

My questions:
- Do you see any typo in the filelist? It looks like the exampled in the wiki page.
- The input files were converted from the gff file after collapsing cogent files and filtering out transcripts with 5' degradation. Am I doing this right? 
- After merging, how do I combine the two fasta files from the two different transcriptome assemblies so that I can map my RNA-seq reads?

Thank you for the help!
Caio

**Comment by sguizard** [comment]
Hi, 
Remove the header in filelist.txt.
The actual version of the program read it.
