### ISSUE TITLE
blastp output format expected

### ISSUE THREAD

**Issue by abayega** [GenomeRIK/tama#5]
Hi, 

for the tama_orf_blastp_parser.py which blastp output format is expected?

Thank you,

**Comment by GenomeRIK** [comment]
Hi abayega! It should be the default output which should have a "bls" file extension. So if you use the command line from the wiki it should give you the bls file. If the bls file isn't working let me know!

**Comment by abayega** [comment]
Hi, 

thanks for the help, and the tool tama. I just directed the default output to a file and then supplied that file to tama_orf_blastp_parser.py. 

I do not understand the output though,

the tama_orf_blastp_parser.py top hits for example include:

G5;G5.1(+)	F1	132	458	45	152	Q9W5E1	full_match	100	94
G5;G5.2(+)	F3	2	58	1	18	none	no_hit	0	0
G5;G5.3(+)	F2	112	438	38	145	Q9W5E1	full_match	100	94
G5;G5.4(+)	F2	103	429	35	142	Q9W5E1	full_match	100	94
G5;G5.5(+)	F1	96	422	33	140	Q9W5E1	full_match	100	94

but the output of tama_cds_regions_bed_add.py for this transcript is:
100705	305	1185	G5;G5.1;none;missing;no_orf;missing;na	40	+	0	0	255,0,0	3	210,28,433	0,276,447
100705	324	970	G5;G5.2;none;missing;no_orf;missing;na	40	+	0	0	255,0,0	3	191,28,218	0,257,428
100705	325	1167	G5;G5.3;none;missing;no_orf;missing;na	40	+	0	0	255,0,0	3	190,28,415	0,256,427
100705	334	1143	G5;G5.4;none;missing;no_orf;missing;na	40	+	0	0	255,0,0	3	181,28,391	0,247,418
100705	341	1102	G5;G5.5;none;missing;no_orf;missing;na	40	+	0	0	255,0,0	3	174,28,350	0,240,411

Why does it say none;missing;no_orf;missing;na when there was a match?
Also, isn't the evalue of blastp set at 1e-10 not too high? I have seen cuts off of 1e-3, do you think 1e-3 is reasonable?

Regards,

**Comment by GenomeRIK** [comment]
Typically you will get the "missing" flag when there is an unknown or wildcard nucleotide in the transcript sequence. Can you check those transcript sequences to see if there are any "N" or wildcard characters in them? Sorry I forgot to add that to the wiki manual. I am still working on the manual and I will add that shortly. 

As for the e value in blastp, feel free to set it to whatever you feel is reasonable for your study. The example is just to show a command that works for giving a usable blastp output. It just depends how lenient or stringent you want to be with your blasting and your use of these predictions. 

Cheers,
Richard

**Comment by abayega** [comment]
Thank you, I will try that

**Comment by GenomeRIK** [comment]
Hi abayega, were you able to confirm the reason for the missing flags?

**Comment by GenomeRIK** [comment]
Ok I am going to close this issue for now, but if you have more problems with this I can reopen it.

**Comment by abayega** [comment]
Hi, sorry for the late reply. I sort of ended up doing it in a different way. It's okay to close it

**Comment by abayega** [comment]
I did blastp locally and parsed the file with local scripts.

**Comment by GenomeRIK** [comment]
Ah ok. Thanks!
