### ISSUE TITLE
Tama Merge colour on UCSC Genome Browser

### ISSUE THREAD

**Issue by SziKayLeung** [GenomeRIK/tama#54]
Hello Richard, 

I really like the feature with the colouring of the transcripts by source from TAMA Merge. However, this only seems to only appear on IGV, and not when I upload the bed file on UCSC Genome Browser. 

Is there a way that the colours can show on the Genome Browser instead?

Thanks! 
Best wishes, 
Szi Kay

**Comment by GenomeRIK** [comment]
Hi Szi Kay,

The color coding is in the 10th column of the bed12 file. So it may be that the UCSC browser is just not using that information. If this is the case then it is something you will need to ask the UCSC Genome Browser developers to build into their browser. 

Thank you,
Richard
