### ISSUE TITLE
TAMA merge - Minimum overlap ratio

### ISSUE THREAD

**Issue by michaelway** [GenomeRIK/tama#55]
Is there any option with tama merge to prevent the merging of transcripts into a single locus (similar to bedtools intersect -r option). In the example below, I have a single incorrect transcript derived from an incorrect sequence on the wrong strand that is merging with a close gene model by just a few bases in a single exon. Is there any setting/option so that these are not merged into the same gene model based on an overlap threshold?
![Slide1](https://user-images.githubusercontent.com/14233708/114898152-c57b0480-9e09-11eb-93bd-054938315d24.jpg)

**Comment by GenomeRIK** [comment]
Hello,

Currently there is no way of thresholding for this in TAMA merge. This idea has come up before but it does not work quite the way people think it would and leads some interesting other complications. I have also seen data like this where it looks like they are different gene loci but after getting more data it reveals that there is actually more overlap and integration than previously seen. So it really depends on what you are actually trying to achieve with this. 

If the reason you are wanting to do this is to get a more accurate gene count then this does not affect the total numbers by a significant degree. If you are finding that it does in your dataset then there are some other things to consider. 

If the reason you are wanting to do this is to just separate this specific case, then you could rename manually.

If the reason you are wanting to do this is to match to a public annotation then you can use the source name feature to just carry of the gene ID's from a reference annotation. 

If the reason you are wanting to do this is to separate by coding sequence, then you can do a separation using the TAMA ORF/NMD pipeline. 

But perhaps it would be better if you could explain what you exact purposes are here?

Thank you,
Richard

**Comment by michaelway** [comment]
Hi richard,

Thanks for the response. That makes sense - just wanted to check encase it was possible directly in tama_merge. 

Best
Mike
