### ISSUE TITLE
The difference between the TAMA and the collapse_isoforms_by_sam.py

### ISSUE THREAD

**Issue by Huangyizhong** [GenomeRIK/tama#57]
Hi, there.
 The TAMA is a good software to deal with the pacbio transcripts, though I do not obtain the final results (the programm is running).  I always used the collapse_isoforms_by_sam.py to collapse the isoforms before, and I found that the isoforms form two near genes may be collapsed into one gene by the collapse_isoforms_by_sam.py. How does the TAMA to deal with this condition? I hava 30 pabcio data, should I merge the bam to continue the process or use the TAMA to collapse them seperately and then merge? If I obtain the bed file, how can I get the gff3 file to add into EVM model to do the gene structures prediction?
Thanks so much!
Sincerely 
Yizhong Huang

**Comment by GenomeRIK** [comment]
Hi Yizhong,

TAMA Collapse and TAMA Merge only put transcripts into the same "gene" group if they overlap on the same strand. 

GFF3 format is not very strict so depending on what you want to use it for you may need a specific GFF3 convertor. If you share a few lines from a GFF3 file that you used for your intended downstream purpose then I can suggest a convertor. 

Cheers,
Richard
