### ISSUE TITLE
Tama merge has so many genes

### ISSUE THREAD

**Issue by Huangyizhong** [GenomeRIK/tama#58]
Hi, there
  Thanks for the TAMA softwares to deal with the PACBIO-data. These days I have runned the tama collapse successfully, and also the tama merge. I have 30 tissues from the PACBIO data and want to merge them. But there were so many genes,whihc makes me so confused? How should I do to deal with it?
Thanks again!
Yizhong Huang 
![image](https://user-images.githubusercontent.com/31943359/121780992-5df8ef80-cbd5-11eb-9633-ca3e2700eceb.png)
![image](https://user-images.githubusercontent.com/31943359/121781000-6b15de80-cbd5-11eb-897e-6e97c70cac10.png)

**Comment by GenomeRIK** [comment]
Hello Yizhong,

Apologies for the very late response. If you still need help with this, could you let me know how many genes you are getting in total and what species this is?

Thank you,
Richard
