### ISSUE TITLE
Tama collapse, Key error: X

### ISSUE THREAD

**Issue by maysonlin** [GenomeRIK/tama#59]
Greetings, 
            I ran into issue while running tama collapse, here is my .log file:
            `tc_version_date_2020_12_14
Default collapse exon ends flag will be used: common_ends
Default coverage: 99inning:     0:0:21
Default identity: 85le
Default identity calculation method: ident_cov
Default 5 prime threshold: 10
Default exon/splice junction threshold: 10
Default 3 prime threshold: 10
Default duplicate merge flag: merge_dup
Default splice junction priority: no_priority
Default splice junction error threshold: 10
Default splice junction local density error threshold: 1000
Default simple error symbol for matches is the underscore "_" .
Using SAM format for reading in.
Default log output on
Default run mode original
Default 5 read threshold
time taken since last check:    0:0:0
time taken since beginning:     0:0:0
going through fasta
time taken since last check:    0:0:21
time taken since beginning:     0:0:21
going through sam file
Traceback (most recent call last):
  File "/home/slin023/.conda/envs/tama/bin/tama_collapse.py", line 5175, in <module>
    [h_count,s_count,i_count,d_count,mis_count,nomatch_dict,sj_pre_error_list,sj_post_error_list] =  calc_error_rate(start_pos,cigar,seq_list,scaff_name,read_id)
  File "/home/slin023/.conda/envs/tama/bin/tama_collapse.py", line 874, in calc_error_rate
    genome_mismatch_list, seq_mismatch_list, nuc_mismatch_list = mismatch_seq(genome_slice, seq_slice, genome_start, seq_start)
  File "/home/slin023/.conda/envs/tama/bin/tama_collapse.py", line 528, in mismatch_seq
    for g_nuc_char in nuc_char_dict[genome_nuc]:
KeyError: 'X'
 
 If you would like to view my script, here is my script submitted to HPC:

`#!/bin/bash
#SBATCH --qos normal
#SBATCH --account acc_jedwell
#SBATCH --partition IB_16C_96G 
#SBATCH -n 16
#SBATCH -N 1
#SBATCH --output=log

module load miniconda3-4.5.11-gcc-8.2.0-oqs2mbg   

source activate tama

tama_collapse.py -s /scratch/mdegenna/slin023/tama/LongSorted.out.sam -f /scratch/mdegenna/slin023/tama/maskedgenome.fasta -p prefix -x capped`

 The PacBio long read aligner sam was sorted and aligned thru minimap :

`#!/bin/bash
#SBATCH --qos normal
#SBATCH --account acc_jedwell
#SBATCH --partition IB_16C_96G 
#SBATCH -n 16
#SBATCH -N 1
#SBATCH --output=log

export PATH=$PATH:/home/slin023/minimap2-2.22_x64-linux

module load samtools-1.9-gcc-8.2.0-o53igvd  

/home/slin023/minimap2-2.22_x64-linux/minimap2 -ax splice:hq -uf /scratch/mdegenna/slin023/minimap/maskedgenome.fasta /scratch/mdegenna/slin023/minimap/m64140_210607_173521.fl.bc1001_5p_bc1001_3p.polished.hq.fasta /scratch/mdegenna/slin023/minimap/m64140_210607_173521.fl.bc1002_5p_bc1002_3p.polished.hq.fasta > aln.sam  

samtools sort /scratch/mdegenna/slin023/minimap/aln.sam -o LongSorted.out.sam`

  Any suggestion is welcomed, thank you in advance!

**Comment by GenomeRIK** [comment]
Hello,

It would seem that you have an "X" character in the genome fasta sequence you supplied. Did you mask with "X"? Or can you find where that X occurs?

Cheers,
Richard

**Comment by maysonlin** [comment]
Yes, I just realized all the characters were supposed to replaced by lower cases, were instead changed to "X" during repeat masker process. Thank you for reminder. In addition, do you recommend to use the masked genome assembly to run tama?

**Comment by GenomeRIK** [comment]
Hello,

I am not sure what genome you are working with so it is hard for me to suggest something. However, I think repeat masking is not as important to have when working with long read data. Repeat masking is mainly done for dealing with the multi-mapping issues with short read which occur at a much lower extent in long read. TAMA also applies filters which should remove any problematic mappings to repeat regions. 

Hope this helps,
Richard
