### ISSUE TITLE
how to calculate coverage & identity value

### ISSUE THREAD

**Issue by paprikachan** [GenomeRIK/tama#6]
Hi,

I am new to Iso-seq and RNA-seq, now I have done PacBio Iso-Seq and alignment, how can I get -c coverage and -i identity?

Thanks a lot.

**Comment by GenomeRIK** [comment]
Hello, 
If you mean what settings to use for -c and - for running TAMA collapse, you can try the default settings first (default -c 99 -i 85). Of course you can play around with these settings to see what happens. 

If you want to know the coverage and identify of mapping for each collapsed transcript model you can find it in the trans_report.txt file. Please see the wiki page for TAMA collapse for the format of the trans_report.txt file (https://github.com/GenomeRIK/tama/wiki/Tama-Collapse).

These are the fields you want:
high_coverage   low_coverage    high_quality_percent    low_quality_percent 

high_coverage   - Highest coverage from pre-collapse support
low_coverage    - Lowest coverage from pre-collapse support
high_quality_percent    - Highest identity from pre-collapse support
low_quality_percent     - Lowestidentity from pre-collapse support

There are currently no outputs for pre-collapsed identity and coverage. If this is something you need, I can add it.

I am not sure if I have answered your question. If not, please let me know. 

Thank you!

**Comment by GenomeRIK** [comment]
Hi Paprikachan, I am going to close this issue for now but if you need more help just reply and I can open it again.
