### ISSUE TITLE
Can TAMA collapse deal with the pacbio transcripts without a reference genome?

### ISSUE THREAD

**Issue by gouwei1** [GenomeRIK/tama#65]
Can TAMA collapse deal with the pacbio transcripts without a reference genome, while its related species has.

**Comment by GenomeRIK** [comment]
Hello,

Unfortunately TAMA requires a reference genome. You may want to take a look at RATTLE:

https://www.biorxiv.org/content/10.1101/2020.02.08.939942v4.full

Cheers,
Richard
