### ISSUE TITLE
Error reading merge.txt file when using tama_read_support_levels.py

### ISSUE THREAD

**Issue by Coldstone0911** [GenomeRIK/tama#66]
Hi Richard,

When I ran tama_read_support_levels.py using the following command:

python tama_read_support_levels.py -f filelist.txt -m tama.merged_merge.txt -o tama.merged.read_support

I got a KeyError:

Default is to flag duplicates and terminate early.
Default is tama flag for TAMA merge file.
opening filelist file
opening merge file
Traceback (most recent call last):
  File "/kulab/scratch/tzutongkao/bin/tama/tama_go/read_support/tama_read_support_levels.py", line 315, in <module>
    read_list = list(source_trans_read_dict[source_name][source_trans_id].keys())
KeyError: 'transcript/81814'

This is my filelist.txt:

SP1	SP1.tama_trans_read.bed	trans_read
SP2	SP2.tama_trans_read.bed	trans_read
SP3	SP3.tama_trans_read.bed	trans_read

This 'transcript/81814' is in the first line of my tama.merged_merge.txt

SP3_Contig_30	39	646	G1.1;SP2_transcript/81814	40	+	39	646	255,0,0	2	273,229	0,378
SP3_Contig_30	191	653	G1.1;SP1_transcript/73027	40	+	191	653	255,0,0	2	121,236	0,226
...

When I tried a different filelist.txt:
1	SP1.tama_trans_read.bed	trans_read
2	SP2.tama_trans_read.bed	trans_read
3	SP3.tama_trans_read.bed	trans_read

A slightly different error message pop out:

Default is to flag duplicates and terminate early.
Default is tama flag for TAMA merge file.
opening filelist file
opening merge file
Traceback (most recent call last):
  File "/kulab/scratch/tzutongkao/bin/tama/tama_go/read_support/tama_read_support_levels.py", line 315, in <module>
    read_list = list(source_trans_read_dict[source_name][source_trans_id].keys())
KeyError: 'SP2'

You addressed a similar issue in #19, but I do have a merge.txt in my situation. Do you have a suggestion about how I should proceed? 

Thank you,
Tzu-Tong

**Comment by GenomeRIK** [comment]
Hello Tzu-Tong,

It looks like you used Cluster in your pipeline. In this case you will need to create a read support levels file from the first TAMA Collapse run for each sample. 

Here is the info from the wiki for doing this:
"Generating read support for TAMA Collapse run where Cluster/Polish reads were used

Filelist.txt

  cluspol       cluster_report.csv     cluster
Command

python tama_read_support_levels.py -f filelist.txt -o tama_collapse_cluster -m trans_read.bed"

After that, you can regenerate read support levels as you go through the levels of processing up to where you are now. 

If you have issues with that let me know. 

Cheers,
Richard

**Comment by Coldstone816** [comment]
Hi Richard,

Thank you for the quick response. I successfully ran "Generating read support for TAMA Collapse run where Cluster/Polish reads were used", however, I am not quite understand how to "regenerate read support levels as you go through the levels of processing up to where you are now"

Without a surprise, when I ran "Generating read support for TAMA Merge run where TAMA Collapse annotations were merged" using the same commands in my question, I got the same error massages.

I also tried to utilize the newly generated tama_collapse_cluster_read_support.txt files of SP1, SP2, and SP3 by "Generating read support for TAMA Merge run where TAMA Merge annotations were merged" (although it doesn't looks right, what I merged was TAMA Collapse annotations, not TAMA Merge annotations)

Command:
python /kulab/scratch/tzutongkao/bin/tama/tama_go/read_support/tama_read_support_levels.py -f filelist.txt -m tama.merged_merge.txt -o tama.merged.read_support

filelist.txt:
SP1	SP1.tama_collapse_cluster_read_support.txt	read_support
SP2	SP2.tama_collapse_cluster_read_support.txt	read_support
SP3	SP3.tama_collapse_cluster_read_support.txt	read_support

Error massage:

Default is to flag duplicates and terminate early.
Default is tama flag for TAMA merge file.
opening filelist file
opening merge file
Traceback (most recent call last):
  File "/kulab/scratch/tzutongkao/bin/tama/tama_go/read_support/tama_read_support_levels.py", line 315, in <module>
    read_list = list(source_trans_read_dict[source_name][source_trans_id].keys())
KeyError: 'transcript/81814'

By the way, here is my tama.merge command:

python /kulab/scratch/tzutongkao/bin/tama/tama_merge.py -f filelist.txt -p tama.merged

filelist.txt for tama.merge:

SP1.tama_trans_read.bed	no_cap	1,1,1	SP1
SP2.tama_trans_read.bed	no_cap	1,1,1	SP2
SP3.tama_trans_read.bed	no_cap	1,1,1	SP3

Thank you,
Tzu-Tong

**Comment by GenomeRIK** [comment]
Hi Tzu-Tong,

Sorry for dropping this. I didn't realize you had replied. 

Are you still working on this? If so let me know and I can open the issue again. 

This is likely to do with the order of generating read support. 

Thank you,
Richard
