### ISSUE TITLE
Find-Model-Changes pipeline

### ISSUE THREAD

**Issue by mictadlo** [GenomeRIK/tama#70]
Hi,
Could you please provide real commands for the [pipeline](https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Find-Model-Changes):
> The full pipeline goes something like this: TAMA Collapse on pipeline A TAMA Collapse on pipeline B Read support on TAMA Collapse on pipeline A Read support on TAMA Collapse on pipeline B TAMA Merge the bed files from TAMA Collapse A and B Read support on the TAMA Merge Now you should have all the files needed to run tama_find_model_changes.py. 

Thank you in advance,

MIchal

**Comment by GenomeRIK** [comment]
Hi Michal,

I do not recommend using the default settings in TAMA as it is designed to be tuned for your specific experiment. Thus I am hesitant to put in real commands for this pipeline because it would encourage people to just copy paste the commands which will likely not be appropriate for their experiment. 

However, if you can tell me more about your data, I can give you suggestions for commands to use. 

Cheers,
Richard

**Comment by mictadlo** [comment]
Hi Richard,
What kind of information do you need about the data?

Thank you in advance,

Michal

**Comment by GenomeRIK** [comment]
Hi Michal,

I would need to know what cDNA generation kit was used, what version of sequencing was used, and what species/sample type the data comes from. 

Cheers,
Richard

**Comment by mictadlo** [comment]
Hi Richard,
Please find attached all XML files. I noticed that both libraries contain plant root data.

Thank you in advance,
Michal 

[m54105_171201_020331.consensusreadset.xml.txt](https://github.com/GenomeRIK/tama/files/8166003/m54105_171201_020331.consensusreadset.xml.txt)
[m54105_171201_020331.sts.xml.txt](https://github.com/GenomeRIK/tama/files/8166004/m54105_171201_020331.sts.xml.txt)
[m54105_171201_020331.subreadset.xml.txt](https://github.com/GenomeRIK/tama/files/8166005/m54105_171201_020331.subreadset.xml.txt)
[m54105_171201_121745.sts.xml.txt](https://github.com/GenomeRIK/tama/files/8166006/m54105_171201_121745.sts.xml.txt)
[m54105_171201_121745.subreadset.xml.txt](https://github.com/GenomeRIK/tama/files/8166007/m54105_171201_121745.subreadset.xml.txt)
l

**Comment by GenomeRIK** [comment]
Hi Michal,

Those files do not provide me with the information I mentioned in my last comment. Do you have that info from someone else in your group? 

Did you run this sequencing or are you getting it from someone else?

Cheers,
Richard

**Comment by GenomeRIK** [comment]
Ok I am closing this now but feel free to open it if you get more info.
