### ISSUE TITLE
the tama bed output further analysis

### ISSUE THREAD

**Issue by NahlaHu** [GenomeRIK/tama#73]
Hi Richard,

So, if we have now the tama output bed files, how bed files can be used to start the transcriptome analysis; in-terms of  detection of new isoforms and evaluation of used reference completeness.

Thanks
Nahla

**Comment by GenomeRIK** [comment]
Hi Nahla,

If you have a reference annotation you want to compare to, you can use TAMA Merge to do the comparison (make sure to read the wiki thoroughly).

You can also feed your annotation bed files into the TAMA ORF/NMD pipeline to get coding region predictions and matching to known proteins. 

Cheers,
Richard

**Comment by NahlaHu** [comment]
Thank you
