### ISSUE TITLE
Error with exon end earlier than exon start

### ISSUE THREAD

**Issue by kudasonya** [GenomeRIK/tama#78]
Hello Richard, 
I am getting this error that people have previously reported when using deSalt, however I am using minimap2. 
I used tama_mapped_sam_splitter.py to split my merged .bam file that was produced using minimap2 and 2passtools:
`minimap2 -ax splice --cs=long -k 13 -t 20 --secondary=yes $sequin_fa --junc-bed 2passtools_out/merged_capture_2pass_filt.bed --junc-bonus 12 merged_capture/merged.fastq | samtools view -Sb -@ 10 > merged_2pass.bam`
`python Tools/tama/tama_go/split_files/tama_mapped_sam_splitter.py merged_2pass.sorted.bam 10 capture_split_2pass`
`tama_collapse.py -s capture_split_2pass_${SLURM_ARRAY_TASK_ID}.sam -f $sequin_fa -p capture_split_2pass_${SLURM_ARRAY_TASK_ID} -x no_cap -c 90 -rm low_mem -icm ident_cov -log log_off -a 200 -m 20`
Would really appreciate some help with this. 
Sofia

**Comment by GenomeRIK** [comment]
Hello Sofia,

Thank you for using TAMA. 

It looks like you are using Nanopore data. Is this correct?

If so, what type of sequencing is this? cDNA, direct RNA?

What data analysis steps did you do before mapping? Which basecaller, trimming, quality filter?

The problem you are seeing can occur with Nanopore data that has been processed a certain way. 

Thank you,
Richard

**Comment by kudasonya** [comment]
Hello Richard, 

Thanks for such a useful tool.
It is indeed cDNA Nanopore data, used Guppy for basecalling + demultiplexing. Your response made me think that maybe I should have stuck with the ident_map option as I have not run adapter trimming. Would you recommend running adapter trimming and then rerunning with ident_cov ? 
Thank you,
Sofia

**Comment by GenomeRIK** [comment]
Hi Sofia,

I recommend the following:

Using the fastq files from Guppy

1.  Filter for read quality above 7 using Seqkit (https://bioinf.shenwei.me/seqkit/)
2. Run Pychopper to remove adapter sequences and orient reads (https://github.com/nanoporetech/pychopper)
3. Use tama_flnc_polya_cleanup.py to remove the poly-A tails (https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Sequence-Cleanup)
4. Map to genome etc.

That should give you much better results and this error should go away when you do that. 

I believe the error you are getting is caused by bad mappings which lead to bad models that TAMA Collapse rejects.

Let me know if you have any other questions. 

Thank you,
Richard

**Comment by kudasonya** [comment]
Hello Richard, 

Thank you for you recommendations. I have run all the QC steps you had suggested, however that did not help with the error. As I understand, something goes wrong at the strand check step. I saw that you previously encountered issues with GMAP and noticed that some of the "failed" read alignments listed in tama logs are missing strand info in the XS:A? field. In addition, some of these reads align to intronic regions and have secondary mappings, which led me to remap them using the minimap --secondary=no option. That did not prevent the error. Could SJ correction done with 2pass have led to this? 
Side question: what method do you recommend for fastq2fasta conversion (to run tama_flnc_polya_cleanup.py)? Conversion using seqtk seems to lead to some reads disappearing. 
Would really appreciate your advice. 

Kind regards, 

Sofia

**Comment by GenomeRIK** [comment]
Hi Sofia,

Sorry for taking so long to respond. Can you send me the info on the 2pass splice junction correction you used? This could be the issue. 

Thank you,
Richard
