### ISSUE TITLE
Order of filter/post-processing steps?

### ISSUE THREAD

**Issue by ejh243** [GenomeRIK/tama#79]
Hi Richard,

Thanks for a great set of tools and really helpful wiki pages.

I have run TAMA collapse on my individuals samples and TAMA merge to combine them into a single dataset. I was wondering if you had any insight into what order to run the downstream filtering steps. I would like to run tama_remove_single_read_models_levels.py, tama_remove_fragment_models.py and the ORF/NMD predictor. Any additional steps you recommend?

My intention is once I get to a curated master transcriptome, I will convert to a gtf so I can align some short read data to it and run sqanti where I can do further filtering. 

Many thanks

**Comment by GenomeRIK** [comment]
Hello,

Apologies for the delayed response. Thank you for using TAMA!

The tools you mentioned sound perfect for what you are trying to achieve and I would run them in that order. 

After you run the ORF/NMD predictor, you could also choose to remove the models that are labelled as degraded if you wish. This can be done with a simple grep -v but let me know if you have any questions about that. 

Thank you,
Richard
