### ISSUE TITLE
converting main bed output to gtf

### ISSUE THREAD

**Issue by olechnwin** [GenomeRIK/tama#82]
Hi,

Thanks for this creating this tool. I have managed to run TAMA merge and get the main bed. Now I am trying to convert the bed to bed to gtf file.
I tried to use 
`bedToGenePred ${bed_name} /dev/stdout | genePredToGtf file /dev/stdin ${bed_name/.bed/}.gtf`

but the resulting gtf have a semicolon inside the id that throws off many tools reading a GTF file including gffread.
This is the error I got from gffread:
```
Error parsing attribute transcript_id ('"' required for GTF) at line:
scaffold_1      /dev/stdin      transcript      26518   28728   .       +       .       gene_id "G1;G1.1"; transcript_id "G1;G1.1";
```
I am wondering whether you have a recommendation on how to properly convert the output bed file from TAMA merge to a gtf format. Thank you in advance for your help !

**Comment by GenomeRIK** [comment]
Hello,

Thank you for using TAMA!

There are several tools in TAMA for converting from bed to GTF. You can find more info on them here:
https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Formatting

Thank you,
Richard

**Comment by olechnwin** [comment]
That makes it easy. Thank you so much!
