### ISSUE TITLE
IndexError: list index out of range tama_filter_primary_transcripts_orf.py

### ISSUE THREAD

**Issue by bijendrabio** [GenomeRIK/tama#85]
Hello,
I received following error while running tama_filter_primary_transcripts_orf.py on tama collapsed bed file. Kindly suggest!.
self.prot_id = id_split[2]
IndexError: list index out of range

**Comment by GenomeRIK** [comment]
Hello,

Thank you for using TAMA. 

Can you show me the exact command line that you used to run the script? I suspect you are using the incorrect input files.

Thank you,
Richard

**Comment by bijendrabio** [comment]
Hello Richard,
Here's a command and error output:
COMMAND LINE:
tama_filter_primary_transcripts_orf.py -b tama_collapse_output.bed -o tama_collapse_output_filter

ERROR:
opening bed file
Traceback (most recent call last):
  File "/home/envs/tama/bin/tama_filter_primary_transcripts_orf.py", line 229, in <module>
    trans_obj.id_parser(id_line)
  File "/home/envs/tama/bin/tama_filter_primary_transcripts_orf.py", line 137, in id_parser
    self.prot_id = id_split[2]
IndexError: list index out of range

**Comment by bijendrabio** [comment]
Hello, 
I am trying to remove overlapping transcripts (isoforms), keeping only the longest ORF containing transcript per gene loci. is there   a way to do this using the available tama supporting scripts?

Regards,
B

**Comment by GenomeRIK** [comment]
Hello B,

You will need to run the TAMA ORF/NMD prediction pipeline as seen here:
https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-ORF-and-NMD-predictions

And then use the output from that pipeline to run "tama_filter_primary_transcripts_orf.py".

Cheers,
Richard
