### ISSUE TITLE
Errors in TAMA GO: Formatting

### ISSUE THREAD

**Issue by anchonggen** [GenomeRIK/tama#86]
Hi,
I tried to convert bed file generated by tama merge to a gtf file by using the command below.
module load biopython/1.66
module load python/2.7.14
/scratch/user/s4613999/tama/tama_go/format_converter/tama_convert_bed_gtf_ensembl_no_cds.py merged_isoseq.bed isoseq_no_cds.gtf
However, it reminded an error as shown below. Could you please help me solve this problem?
![image](https://user-images.githubusercontent.com/115862778/202954892-7bd63a4e-0c38-4025-817c-e1d0a93afa36.png)

Thank you!

An

**Comment by anchonggen** [comment]
Also, under Linux environment, which column of the merged bed file generated by TAMA Merge does indicate source sample information?

**Comment by GenomeRIK** [comment]
Hello An,

Thank you for using TAMA.

It looks like the issue has to do with your computing system or with the way you setup TAMA. It looks like you are using a university high performance computing cluster so you may want to ask your admins for help on setting your environment up correctly.

Are you at the University of Edinburgh?

Regarding the second question, the merged bed file does not contain the source information. You have to look at the other output files. Please read the wiki page for TAMA Merge:

https://github.com/GenomeRIK/tama/wiki/Tama-Merge

Thank you,
Richard

**Comment by anchonggen** [comment]
Thank you for your reply. 
I am at the University of Queensland. Yes. The issue has to do with the university computing system, as it ran well on my personal computer.
