### ISSUE TITLE
how to cite this work?

### ISSUE THREAD

**Issue by YuntaoTan** [GenomeRIK/tama#9]
@GenomeRIK   you do a hard work for this , how to cite this work?

**Comment by GenomeRIK** [comment]
Hello Yuntao, thank you very much! We are working on the paper now and hope to submit by March. I will submit a pre-print first on Bioarxiv for people who need to cite the tool sooner. I really appreciate your interest in TAMA and your consideration for citing this tool.

**Comment by chenzler** [comment]
Any update on this? We used TAMA in a manuscript we'll be submitting soon, and would like to cite the pre-print or publication if possible!

**Comment by GenomeRIK** [comment]
Hi Chenzler, I am hoping to submit a pre-print to Biorxiv in a couple weeks (definitely before the end of July). For now I am just asking people to cite the github and then change to the pre-print when it is out. 

The authors of this pre-print did that:
https://www.biorxiv.org/content/10.1101/478172v1.full

Thank you for citing!

**Comment by GenomeRIK** [comment]
Hi YuntaoTan and chenzler,

The Biorxiv pre-print is finally out. You can use this to cite TAMA:
https://www.biorxiv.org/content/10.1101/780015v1

Thank you for citing!
Richard
