### ISSUE TITLE
TAMA GO: ORF and NMD predictions

### ISSUE THREAD

**Issue by anchonggen** [GenomeRIK/tama#92]
Hi,
I would like to ask if TAMA GO: ORF and NMD predictions are available to predict lncRNAs.

Thanks,
An

**Comment by GenomeRIK** [comment]
Hi An,

The TAMA ORF/NMD pipeline finds protein hits and CDS for the transcript models. If a transcript model has no hits this could be interpreted as possible a lncRNA. However, there are different ways of predicting lncRNA, so in general it is best to use a variety of methods to see what is consensus. 

Thank you,
Richard
