### ISSUE TITLE
TAMA Merge Parameters

### ISSUE THREAD

**Issue by OEveSalar** [GenomeRIK/tama#93]
Hi Richard,

Thanks for the suite of tools! I have a question about TAMA Merge parameters.
I have carried out nanopore RNA-seq (DCS109 w/ native barcoding) on 18 samples for an immune challenge study. I have 3 conditions; Control, Vibrio, PolyIC, and n=6 biological replicates for each condition. The processing steps I’ve already taken are:
-	Basecalled with Guppy
-	Filtered low quality reads (q<10) with nanofilt
-	Demultiplexed with Guppy
-	Filtered (supposedly) ‘full-length’ reads with Pychopper
-	Trimmed polyA tails with CutAdapt
-	Mapped to genome with Minimap2
-	Collapsed each sample individually with TAMA_Collapse with the script below:

![image](https://user-images.githubusercontent.com/77499554/212310893-35b81325-ea7d-4720-bca6-d373ded67b8f.png)

Now, I would like to merge my samples together to form one large transcriptome that I can take forward and compare to the existing reference. I understand I can use TAMA merge to do this but I’m unsure on the parameters required. I think I should be using the default TAMA_Merge parameters except I should be using –d merge_dup? Is this correct? Secondly, in my filelist.txt, I think I will use the no_cap flag rather than capped, however, I’m unsure of this as I used no_cap in TAMA_Collapse. Will I lose information by using the no_cap flag again in TAMA_Merge?

My next steps would be to filter out models with low read support (<3), filter out single-exon models with low read support (<50) and then use SQANTI3 to get a comparison between my long-read transcriptome and the existing reference. Does this sound sensible?

Many thanks and sorry for the long question!
Oliver

**Comment by GenomeRIK** [comment]
Hi Oliver,

Thank you for using TAMA! And apologies for not responding sooner. 

Very cool pipeline you have put together!

The answers to your questions are exactly simply. It depends a lot on what exactly you want to achieve. 

However in general I would say:

>>I think I should be using the default TAMA_Merge parameters except I should be using –d merge_dup? Is this correct? 

I recommend running TAMA Merge with –d merge_dup -a 100 -x 10 -z 100

>>Secondly, in my filelist.txt, I think I will use the no_cap flag rather than capped, however, I’m unsure of this as I used no_cap in TAMA_Collapse. Will I lose information by using the no_cap flag again in TAMA_Merge?

If you used no_cap in TAMA Collapse then I would use no_cap in TAMA Merge. Because your library is likely going to have significant degradation so any isoform level information that could be identified with the capped mode would not be very certain. Did you happen to run Deg Sig on your data?

>>My next steps would be to filter out models with low read support (<3), filter out single-exon models with low read support (<50) and then use SQANTI3 to get a comparison between my long-read transcriptome and the existing reference. Does this sound sensible?

This is really up to you. It is a bit more conservative than I usually do (50 reads is a lot for nanopore) but that's fine if would want more stringency. As for using SQANTI3, I think that's a good idea although admittedly I have not been keeping up with current SQANTI3 features. You could also try using TAMA Merge to compare with the reference but that is more hands on for downstream analysis whereas SQANTI3 does a great job at auto running a lot of downstream stuff. 


Hope that helps!
Richard

**Comment by MR-D-CJ** [comment]
> Hi Richard,  嗨，理查德，
> 
> Thanks for the suite of tools! I have a question about TAMA Merge parameters.感谢这套工具！我对 TAMA Merge 参数有疑问。 I have carried out nanopore RNA-seq (DCS109 w/ native barcoding) on 18 samples for an immune challenge study. I have 3 conditions; Control, Vibrio, PolyIC, and n=6 biological replicates for each condition. The processing steps I’ve already taken are:我已经对 18 个样本进行了纳米孔 RNA 测序（DCS109，带原生条形码），用于免疫挑战研究。我有 3 种条件：对照、弧菌、PolyIC，每种条件 n=6 个生物学重复。我已经采取的处理步骤如下：
> 
> * Basecalled with Guppy  使用 Guppy 进行 Basecalling
> * Filtered low quality reads (q<10) with nanofilt使用纳米过滤技术过滤低质量读数（q<10）
> * Demultiplexed with Guppy  使用 Guppy 进行解复用
> * Filtered (supposedly) ‘full-length’ reads with Pychopper使用 Pychopper 过滤（据称）“全长”读取
> * Trimmed polyA tails with CutAdapt使用 CutAdapt 修剪 polyA 尾巴
> * Mapped to genome with Minimap2使用 Minimap2 映射到基因组
> * Collapsed each sample individually with TAMA_Collapse with the script below:使用以下脚本通过 TAMA_Collapse 单独折叠每个样本：
> 
> ![image](https://user-images.githubusercontent.com/77499554/212310893-35b81325-ea7d-4720-bca6-d373ded67b8f.png)
> 
> Now, I would like to merge my samples together to form one large transcriptome that I can take forward and compare to the existing reference. I understand I can use TAMA merge to do this but I’m unsure on the parameters required. I think I should be using the default TAMA_Merge parameters except I should be using –d merge_dup? Is this correct? Secondly, in my filelist.txt, I think I will use the no_cap flag rather than capped, however, I’m unsure of this as I used no_cap in TAMA_Collapse. Will I lose information by using the no_cap flag again in TAMA_Merge?现在，我想将我的样本合并在一起，形成一个大的转录组，以便我可以继续进行并与现有参考进行比较。我知道我可以使用 TAMA 合并来执行此操作，但我不确定所需的参数。我认为我应该使用默认的 TAMA_Merge 参数，但我应该使用 –d merge_dup？这样对吗？其次，在我的 filelist.txt 中，我想我会使用 no_cap 标志而不是 capped，但是，我不确定这一点，因为我在 TAMA_Collapse 中使用了 no_cap。在 TAMA_Merge 中再次使用 no_cap 标志会丢失信息吗？
> 
> My next steps would be to filter out models with low read support (<3), filter out single-exon models with low read support (<50) and then use SQANTI3 to get a comparison between my long-read transcriptome and the existing reference. Does this sound sensible?我的下一步是过滤掉读取支持度低的模型（<3），过滤掉读取支持度低的单外显子模型（<50），然后使用 SQANTI3 比较我的长读取转录组和现有参考。这听起来合理吗？
> 
> Many thanks and sorry for the long question!非常感谢，抱歉问了这么长的问题！ Oliver  奥利弗

Hello, I would like to ask what file generated by TAMA merge can be used as the input file of SQANTi3, and do you need to adjust the format
